using AiUsageHud.Core.Models;

namespace AiUsageHud.Core.Theming;

/// <summary>
/// The 15 named colors of a theme palette, as #RRGGBB hex strings. Single source of
/// truth shared by the UI: the Avalonia palette dictionaries (*.axaml) and the
/// Settings theme swatches all derive from this table.
/// Generated by tools/Generate-Palettes.ps1 from tools/palettes.json — do not edit by hand.
/// </summary>
public sealed record PaletteColors(string Bg, string Bg2, string Bg3, string Hover, string Fg, string Dim, string Accent, string Border, string BarEmpty, string SevLow, string SevMid, string SevHigh, string SevCritical, string CloseHover, string ClosePressed)
{
    /// <summary>Palette colors for every theme, keyed by id.</summary>
    public static IReadOnlyDictionary<ThemeId, PaletteColors> All { get; } = new Dictionary<ThemeId, PaletteColors>
    {
        [ThemeId.Amoled] = new("#000000", "#000000", "#0E0E0E", "#181818", "#FFFFFF", "#6B6B6B", "#B388FF", "#282828", "#282828", "#00FF88", "#FFEA00", "#FF8022", "#FF1744", "#FF1744", "#D7001C"),
        [ThemeId.Aura] = new("#15141B", "#0D0C13", "#232229", "#2D2C33", "#EDECEE", "#706F74", "#A277FF", "#3D3C43", "#3D3C43", "#61FFCA", "#FFCA85", "#FF9876", "#FF6767", "#FF6767", "#D73F3F"),
        [ThemeId.AyuDark] = new("#0A0E14", "#0B101A", "#1B222D", "#273142", "#B3B1AD", "#4D5566", "#E6B450", "#273142", "#1B222D", "#AAD94C", "#E6B450", "#FF8F40", "#F26D78", "#F26D78", "#D95E68"),
        [ThemeId.AyuLight] = new("#FAFAFA", "#F3F4F5", "#E6E8EA", "#C4C6C9", "#5C6166", "#ABB0B6", "#F2AE49", "#C4C6C9", "#E6E8EA", "#86B300", "#F2AE49", "#FA8D3E", "#F07178", "#F07178", "#D95E68"),
        [ThemeId.AyuMirage] = new("#1F2430", "#191E2A", "#232834", "#2D3441", "#CBCCC6", "#707A8C", "#5CCFE6", "#2D3441", "#232834", "#BAE67E", "#FFD580", "#FFA759", "#FF6666", "#FF6666", "#E04F4F"),
        [ThemeId.Carbonfox] = new("#393939", "#313131", "#474747", "#515151", "#F2F4F8", "#878889", "#33B1FF", "#616161", "#616161", "#42BE65", "#F1C21B", "#F8A252", "#FF8389", "#FF8389", "#D75B61"),
        [ThemeId.CatppuccinLatte] = new("#EFF1F5", "#E6E9EF", "#DCE0E8", "#CCD0DA", "#4C4F69", "#8C8FA1", "#1E66F5", "#CCD0DA", "#CCD0DA", "#40A02B", "#DF8E1D", "#FE640B", "#D20F39", "#D20F39", "#B00C30"),
        [ThemeId.CatppuccinMacchiato] = new("#24273A", "#1E2030", "#363A4F", "#494D64", "#CAD3F5", "#6E738D", "#8AADF4", "#494D64", "#363A4F", "#A6DA95", "#EED49F", "#F5A97F", "#ED8796", "#ED8796", "#D96E7E"),
        [ThemeId.CatppuccinMocha] = new("#1E1E2E", "#181825", "#313244", "#45475A", "#CDD6F4", "#6C7086", "#89B4FA", "#313244", "#313244", "#A6E3A1", "#F9E2AF", "#FAB387", "#F38BA8", "#F38BA8", "#E64D6F"),
        [ThemeId.Cobalt2] = new("#193549", "#122738", "#1F4662", "#234E6D", "#E1EFFF", "#627E97", "#FFC600", "#234E6D", "#1F4662", "#3AD900", "#FFC600", "#FF9D00", "#FF628C", "#FF628C", "#E04A72"),
        [ThemeId.Cursor] = new("#181818", "#101010", "#262626", "#303030", "#E4E4E4", "#6E6E6E", "#88C0D0", "#404040", "#404040", "#3FA266", "#F1B467", "#EA7D6C", "#E34671", "#E34671", "#BB1E49"),
        [ThemeId.Cyberpunk] = new("#120B2E", "#0A061C", "#281745", "#3D2660", "#F0F6F0", "#867C9D", "#FF007F", "#281745", "#281745", "#00FF99", "#FDF900", "#FF8F00", "#FF003C", "#FF003C", "#C2002E"),
        [ThemeId.Darcula] = new("#2B2B2B", "#242424", "#3C3F41", "#4B4D4D", "#A9B7C6", "#808080", "#CC7832", "#555555", "#3C3F41", "#629755", "#FFC66D", "#E88934", "#CC666E", "#CC666E", "#A85055"),
        [ThemeId.Dracula] = new("#282A36", "#21222C", "#343746", "#44475A", "#F8F8F2", "#6272A4", "#BD93F9", "#44475A", "#44475A", "#50FA7B", "#F1FA8C", "#FFB86C", "#FF5555", "#FF5555", "#D63E3E"),
        [ThemeId.DraculaPro] = new("#22212C", "#1B1A23", "#2D2B3B", "#454158", "#F8F8F2", "#7970A9", "#9580FF", "#454158", "#2D2B3B", "#8AFF80", "#FFFF80", "#FFCA80", "#FF9580", "#FF9580", "#E07A66"),
        [ThemeId.EverforestDark] = new("#2D353B", "#272E33", "#343F44", "#3D484D", "#D3C6AA", "#859289", "#7FBBB3", "#3D484D", "#343F44", "#A7C080", "#DBBC7F", "#E69875", "#E67E80", "#E67E80", "#CC6668"),
        [ThemeId.Flexoki] = new("#100F0F", "#080707", "#1E1D1D", "#282727", "#CECDC3", "#6F6E69", "#DA702C", "#383737", "#383737", "#879A39", "#DA702C", "#D65E36", "#D14D41", "#D14D41", "#A92519"),
        [ThemeId.FluentDark] = new("#202020", "#1C1C1C", "#2D2D2D", "#383838", "#FFFFFF", "#9D9D9D", "#60CDFF", "#393939", "#2D2D2D", "#6CCB5F", "#FCE100", "#FF8C00", "#FF5459", "#C42B1C", "#A52317"),
        [ThemeId.FluentLight] = new("#F3F3F3", "#EAEAEA", "#FBFBFB", "#EDEDED", "#1A1A1A", "#5C5C5C", "#005FB8", "#E0E0E0", "#E5E5E5", "#0F7B0F", "#9D5D00", "#C4500B", "#C42B1C", "#C42B1C", "#A52317"),
        [ThemeId.GitHubDark] = new("#0D1117", "#010409", "#161B22", "#21262D", "#C9D1D9", "#8B949E", "#58A6FF", "#30363D", "#21262D", "#3FB950", "#D29922", "#DB6D28", "#F85149", "#F85149", "#DA3633"),
        [ThemeId.GitHubLight] = new("#FFFFFF", "#F6F8FA", "#EBF0F4", "#EAEEF2", "#24292F", "#57606A", "#0969DA", "#D0D7DE", "#EAEEF2", "#2DA44E", "#BF8700", "#E36209", "#CF222E", "#CF222E", "#A40E26"),
        [ThemeId.GruvboxDark] = new("#282828", "#1D2021", "#3C3836", "#504945", "#EBDBB2", "#928374", "#83A598", "#504945", "#3C3836", "#B8BB26", "#FABD2F", "#FE8019", "#FB4934", "#FB4934", "#CC241D"),
        [ThemeId.GruvboxLight] = new("#FBF1C7", "#F2E5BC", "#EBDBB2", "#D5C4A1", "#3C3836", "#7C6F64", "#458588", "#D5C4A1", "#EBDBB2", "#98971A", "#D79921", "#D65D0E", "#CC241D", "#CC241D", "#9D0006"),
        [ThemeId.Horizon] = new("#1C1E26", "#161821", "#2E303E", "#3D4054", "#D5C8C6", "#8D8B9B", "#E95678", "#2E303E", "#2E303E", "#29D398", "#FAC29A", "#FAB795", "#E95678", "#E95678", "#B33D5B"),
        [ThemeId.Kanagawa] = new("#1F1F28", "#16161D", "#2A2A37", "#363646", "#DCD7BA", "#727169", "#7E9CD8", "#2A2A37", "#2A2A37", "#98BB6C", "#E6C384", "#FFA066", "#FF5D62", "#FF5D62", "#E04A50"),
        [ThemeId.MaterialOcean] = new("#0F111A", "#090B10", "#1A1C23", "#282A36", "#8F93A2", "#4B5263", "#82AAFF", "#282A36", "#1A1C23", "#C3E88D", "#FFCB6B", "#F78C6C", "#FF5370", "#FF5370", "#E04860"),
        [ThemeId.MaterialPalenight] = new("#292D3E", "#222637", "#34394D", "#3C4254", "#A6ACCD", "#676E95", "#82AAFF", "#3C4254", "#34394D", "#C3E88D", "#FFCB6B", "#F78C6C", "#FF5370", "#FF5370", "#E04860"),
        [ThemeId.Matrix] = new("#0A0E0A", "#020602", "#181C18", "#222622", "#62FF94", "#8CA391", "#2EFF6A", "#323632", "#323632", "#62FF94", "#E6FF57", "#F2A551", "#FF4B4B", "#FF4B4B", "#D72323"),
        [ThemeId.Mercury] = new("#171721", "#0F0F19", "#25252F", "#2F2F39", "#DDDDE5", "#9D9DA8", "#8DA4F5", "#3F3F49", "#3F3F49", "#77C599", "#FC9B6F", "#FC9692", "#FC92B4", "#FC92B4", "#D46A8C"),
        [ThemeId.Monokai] = new("#272822", "#1E1F1C", "#3E3D32", "#49483E", "#F8F8F2", "#75715E", "#66D9EF", "#49483E", "#3E3D32", "#A6E22E", "#E6DB74", "#FD971F", "#F92672", "#F92672", "#C71C5E"),
        [ThemeId.MonokaiPro] = new("#2D2A2E", "#221F22", "#403E41", "#5B595C", "#FCFCFA", "#727072", "#FFD866", "#5B595C", "#403E41", "#A9DC76", "#FFD866", "#FC9867", "#FF6188", "#FF6188", "#E04C70"),
        [ThemeId.NightOwl] = new("#011627", "#010E1A", "#0B2942", "#1D3B53", "#D6DEEB", "#5F7E97", "#82AAFF", "#1D3B53", "#0B2942", "#22DA6E", "#ECC48D", "#F78C6C", "#EF5350", "#EF5350", "#C9302C"),
        [ThemeId.NightOwlLight] = new("#FBFBFB", "#F0F0F0", "#E0E0E0", "#D3D3D3", "#403F53", "#90A7B2", "#0C969B", "#E0E0E0", "#E0E0E0", "#08916A", "#E0BC1E", "#F76E6E", "#DE3D3B", "#DE3D3B", "#B52F2D"),
        [ThemeId.Nord] = new("#2E3440", "#272B35", "#3B4252", "#434C5E", "#D8DEE9", "#6C7589", "#88C0D0", "#434C5E", "#3B4252", "#A3BE8C", "#EBCB8B", "#D08770", "#BF616A", "#BF616A", "#A54852"),
        [ThemeId.Oc2] = new("#1F1F1F", "#171717", "#2D2D2D", "#373737", "#F1ECE8", "#707070", "#FAB283", "#474747", "#474747", "#12C905", "#FCD53A", "#FC943A", "#FC533A", "#FC533A", "#D42B12"),
        [ThemeId.OceanicNext] = new("#1B2B34", "#121C22", "#253B47", "#343D46", "#CDD3DE", "#65737E", "#6699CC", "#343D46", "#253B47", "#99C794", "#FAC863", "#F99157", "#EC5F67", "#EC5F67", "#C14B52"),
        [ThemeId.OneDark] = new("#282C34", "#21252B", "#2C313A", "#323842", "#ABB2BF", "#5C6370", "#61AFEF", "#3E4451", "#3E4451", "#98C379", "#E5C07B", "#D19A66", "#E06C75", "#E06C75", "#BE5046"),
        [ThemeId.OneDarkPro] = new("#1E222A", "#161A22", "#2C3038", "#363A42", "#ABB2BF", "#595E69", "#61AFEF", "#464A52", "#464A52", "#98C379", "#E5C07B", "#E29678", "#E06C75", "#E06C75", "#B8444D"),
        [ThemeId.OneLight] = new("#FAFAFA", "#EAEAEB", "#F0F0F1", "#E1E1E3", "#383A42", "#9D9DA3", "#4078F2", "#D3D3D5", "#D3D3D5", "#50A14F", "#C18401", "#D75F00", "#E45649", "#E45649", "#C73E36"),
        [ThemeId.OpenCode] = new("#0A0A0A", "#020202", "#181818", "#222222", "#EEEEEE", "#808080", "#FAB283", "#323232", "#323232", "#7FD88F", "#F5A742", "#EA8A5C", "#E06C75", "#E06C75", "#B8444D"),
        [ThemeId.Orng] = new("#0A0A0A", "#020202", "#181818", "#222222", "#EEEEEE", "#808080", "#EC5B2B", "#323232", "#323232", "#6BA1E6", "#EC5B2B", "#E66450", "#E06C75", "#E06C75", "#B8444D"),
        [ThemeId.OsakaJade] = new("#111C18", "#091410", "#1F2A26", "#293430", "#C1C497", "#53685B", "#2DD5B7", "#394440", "#394440", "#549E6A", "#E5C736", "#F28D3E", "#FF5345", "#FF5345", "#D72B1D"),
        [ThemeId.Palenight] = new("#292D3E", "#212536", "#373B4C", "#414556", "#A6ACCD", "#676E95", "#82AAFF", "#515566", "#515566", "#C3E88D", "#FFCB6B", "#F89E72", "#F07178", "#F07178", "#C84950"),
        [ThemeId.Panda] = new("#292A2B", "#242526", "#3A3B3C", "#424344", "#E6E6E6", "#676B79", "#19F9D8", "#424344", "#3A3B3C", "#19F9D8", "#FFCC95", "#FFB86C", "#FF2C6D", "#FF2C6D", "#D12057"),
        [ThemeId.Poimandres] = new("#1B1E28", "#171922", "#303340", "#3A3F58", "#A6ACCD", "#767C9D", "#5DE4C7", "#303340", "#303340", "#5DE4C7", "#FFFAC2", "#F087BD", "#D0679D", "#D0679D", "#A64C7A"),
        [ThemeId.RosePine] = new("#191724", "#1F1D2E", "#26233A", "#2A283E", "#E0DEF4", "#6E6A86", "#C4A7E7", "#26233A", "#26233A", "#9CCFD8", "#F6C177", "#EBBCBA", "#EB6F92", "#EB6F92", "#D1577D"),
        [ThemeId.RosePineDawn] = new("#FAF4ED", "#FFFAF3", "#F2E9E1", "#DFDAD9", "#575279", "#9893A5", "#907AA9", "#DFDAD9", "#F2E9E1", "#56949F", "#EA9D34", "#D7827E", "#B4637A", "#B4637A", "#97516A"),
        [ThemeId.ShadesOfPurple] = new("#1A102B", "#120823", "#281E39", "#322843", "#F5F0FF", "#766E84", "#C792FF", "#423853", "#423853", "#7BE0B0", "#FFD580", "#FFA8A3", "#FF7AC6", "#FF7AC6", "#D7529E"),
        [ThemeId.Snazzy] = new("#282A36", "#21222C", "#3A3D4D", "#4D5166", "#EFF0EB", "#78787E", "#FF5C57", "#3A3D4D", "#3A3D4D", "#5AF78E", "#F3F99D", "#FF9F43", "#FF5C57", "#FF5C57", "#C94240"),
        [ThemeId.SolarizedDark] = new("#002B36", "#00252E", "#073642", "#0A4452", "#93A1A1", "#586E75", "#268BD2", "#073642", "#073642", "#859900", "#B58900", "#CB4B16", "#DC322F", "#DC322F", "#B72824"),
        [ThemeId.SolarizedLight] = new("#FDF6E3", "#EEE8D5", "#E7E0CB", "#DDD6C1", "#657B83", "#93A1A1", "#268BD2", "#DDD6C1", "#E7E0CB", "#859900", "#B58900", "#CB4B16", "#DC322F", "#DC322F", "#B72824"),
        [ThemeId.Synthwave84] = new("#262335", "#1E1A2B", "#2A2640", "#34294F", "#F8F8F2", "#6D6886", "#FF7EDB", "#34294F", "#2A2640", "#72F1B8", "#FEDE5D", "#FF8B39", "#FE4450", "#FE4450", "#D63647"),
        [ThemeId.TokyoNight] = new("#1A1B26", "#16161E", "#24283B", "#2F3549", "#C0CAF5", "#565F89", "#7AA2F7", "#2F3549", "#24283B", "#9ECE6A", "#E0AF68", "#FF9E64", "#F7768E", "#F7768E", "#DB5E78"),
        [ThemeId.TokyoNightStorm] = new("#24283B", "#1F2335", "#292E42", "#343A52", "#C0CAF5", "#565F89", "#7AA2F7", "#343A52", "#292E42", "#9ECE6A", "#E0AF68", "#FF9E64", "#F7768E", "#F7768E", "#DB5E78"),
        [ThemeId.Vercel] = new("#000000", "#000000", "#0E0E0E", "#181818", "#EDEDED", "#878787", "#0070F3", "#282828", "#282828", "#46A758", "#FFB224", "#F27D38", "#E5484D", "#E5484D", "#BD2025"),
        [ThemeId.Vesper] = new("#101010", "#080808", "#1E1E1E", "#282828", "#FFFFFF", "#8B8B8B", "#FFC799", "#383838", "#383838", "#99FFE4", "#FFC799", "#FFA48C", "#FF8080", "#FF8080", "#D75858"),
        [ThemeId.WinterIsComing] = new("#011627", "#010E1A", "#0B2942", "#1D3B53", "#A7DBD8", "#5F7E97", "#5F87B6", "#1D3B53", "#0B2942", "#C792EA", "#ECC48D", "#F78C6C", "#EF5350", "#EF5350", "#C9302C"),
        [ThemeId.Zenburn] = new("#3F3F3F", "#373737", "#4D4D4D", "#575757", "#DCDCCC", "#9F9F9F", "#8CD0D3", "#676767", "#676767", "#7F9F7F", "#F0DFAF", "#DEB9A1", "#CC9393", "#CC9393", "#A46B6B"),
    };

    /// <summary>The palette for a theme (falls back to One Dark for an unknown id).</summary>
    public static PaletteColors For(ThemeId id) => All.TryGetValue(id, out var p) ? p : All[ThemeId.OneDark];
}
