namespace AiUsageBar.Core.Models;

/// <summary>
/// Selectable UI color theme. Each member maps to a palette resource dictionary in
/// the app (<c>Themes/Palettes/*.xaml</c>); <see cref="ThemeIdExtensions.Slug"/> is
/// the lowercase form persisted to <c>[ui].theme</c> in config.
/// </summary>
public enum ThemeId
{
    OneDark,
    OneLight,
    FluentDark,
    FluentLight,
    Nord,
    Dracula,
    SolarizedDark,
    SolarizedLight,
    GruvboxDark,
    TokyoNight,
    Monokai,
    CatppuccinMocha,
    CatppuccinLatte,
    GitHubDark,
    MaterialPalenight,
    AyuMirage,
    RosePine,
    TokyoNightStorm,
    GruvboxLight,
    NightOwl,
    Cobalt2,
    EverforestDark,
    RosePineDawn,
    Synthwave84,
    Kanagawa,
    OpenCode,
    Vesper,
    Aura,
    Matrix,
    Zenburn,
    Flexoki,
    Carbonfox,
    ShadesOfPurple,
    Vercel,
    OsakaJade,
    Amoled,
    Mercury,
    Cursor,
    OneDarkPro,
    Palenight,
    Orng,
    Oc2,
    AyuDark,
    AyuLight,
    CatppuccinMacchiato,
    MaterialOcean,
    MonokaiPro,
    GitHubLight,
    WinterIsComing,
    OceanicNext,
    Panda,
    Darcula,
    DraculaPro,
    Poimandres,
    Horizon,
    Cyberpunk,
    Snazzy,
    NightOwlLight,
}

public static class ThemeIdExtensions
{
    /// <summary>Lowercase, kebab-case slug used in config and to locate the palette file.</summary>
    public static string Slug(this ThemeId id) => id switch
    {
        ThemeId.OneDark => "one-dark",
        ThemeId.OneLight => "one-light",
        ThemeId.FluentDark => "fluent-dark",
        ThemeId.FluentLight => "fluent-light",
        ThemeId.Nord => "nord",
        ThemeId.Dracula => "dracula",
        ThemeId.SolarizedDark => "solarized-dark",
        ThemeId.SolarizedLight => "solarized-light",
        ThemeId.GruvboxDark => "gruvbox-dark",
        ThemeId.TokyoNight => "tokyo-night",
        ThemeId.Monokai => "monokai",
        ThemeId.CatppuccinMocha => "catppuccin-mocha",
        ThemeId.CatppuccinLatte => "catppuccin-latte",
        ThemeId.GitHubDark => "github-dark",
        ThemeId.MaterialPalenight => "material-palenight",
        ThemeId.AyuMirage => "ayu-mirage",
        ThemeId.RosePine => "rose-pine",
        ThemeId.TokyoNightStorm => "tokyo-night-storm",
        ThemeId.GruvboxLight => "gruvbox-light",
        ThemeId.NightOwl => "night-owl",
        ThemeId.Cobalt2 => "cobalt2",
        ThemeId.EverforestDark => "everforest-dark",
        ThemeId.RosePineDawn => "rose-pine-dawn",
        ThemeId.Synthwave84 => "synthwave-84",
        ThemeId.Kanagawa => "kanagawa",
        ThemeId.OpenCode => "opencode",
        ThemeId.Vesper => "vesper",
        ThemeId.Aura => "aura",
        ThemeId.Matrix => "matrix",
        ThemeId.Zenburn => "zenburn",
        ThemeId.Flexoki => "flexoki",
        ThemeId.Carbonfox => "carbonfox",
        ThemeId.ShadesOfPurple => "shades-of-purple",
        ThemeId.Vercel => "vercel",
        ThemeId.OsakaJade => "osaka-jade",
        ThemeId.Amoled => "amoled",
        ThemeId.Mercury => "mercury",
        ThemeId.Cursor => "cursor",
        ThemeId.OneDarkPro => "one-dark-pro",
        ThemeId.Palenight => "palenight",
        ThemeId.Orng => "orng",
        ThemeId.Oc2 => "oc-2",
        ThemeId.AyuDark => "ayu-dark",
        ThemeId.AyuLight => "ayu-light",
        ThemeId.CatppuccinMacchiato => "catppuccin-macchiato",
        ThemeId.MaterialOcean => "material-ocean",
        ThemeId.MonokaiPro => "monokai-pro",
        ThemeId.GitHubLight => "github-light",
        ThemeId.WinterIsComing => "winter-is-coming",
        ThemeId.OceanicNext => "oceanic-next",
        ThemeId.Panda => "panda",
        ThemeId.Darcula => "darcula",
        ThemeId.DraculaPro => "dracula-pro",
        ThemeId.Poimandres => "poimandres",
        ThemeId.Horizon => "horizon",
        ThemeId.Cyberpunk => "cyberpunk",
        ThemeId.Snazzy => "snazzy",
        ThemeId.NightOwlLight => "night-owl-light",
        _ => "one-dark",
    };

    /// <summary>Human label shown in Settings.</summary>
    public static string Label(this ThemeId id) => id switch
    {
        ThemeId.OneDark => "One Dark",
        ThemeId.OneLight => "One Light",
        ThemeId.FluentDark => "Fluent Dark",
        ThemeId.FluentLight => "Fluent Light",
        ThemeId.Nord => "Nord",
        ThemeId.Dracula => "Dracula",
        ThemeId.SolarizedDark => "Solarized Dark",
        ThemeId.SolarizedLight => "Solarized Light",
        ThemeId.GruvboxDark => "Gruvbox Dark",
        ThemeId.TokyoNight => "Tokyo Night",
        ThemeId.Monokai => "Monokai",
        ThemeId.CatppuccinMocha => "Catppuccin Mocha",
        ThemeId.CatppuccinLatte => "Catppuccin Latte",
        ThemeId.GitHubDark => "GitHub Dark",
        ThemeId.MaterialPalenight => "Material Palenight",
        ThemeId.AyuMirage => "Ayu Mirage",
        ThemeId.RosePine => "Rosé Pine",
        ThemeId.TokyoNightStorm => "Tokyo Night Storm",
        ThemeId.GruvboxLight => "Gruvbox Light",
        ThemeId.NightOwl => "Night Owl",
        ThemeId.Cobalt2 => "Cobalt2",
        ThemeId.EverforestDark => "Everforest Dark",
        ThemeId.RosePineDawn => "Rosé Pine Dawn",
        ThemeId.Synthwave84 => "Synthwave '84",
        ThemeId.Kanagawa => "Kanagawa",
        ThemeId.OpenCode => "OpenCode",
        ThemeId.Vesper => "Vesper",
        ThemeId.Aura => "Aura",
        ThemeId.Matrix => "Matrix",
        ThemeId.Zenburn => "Zenburn",
        ThemeId.Flexoki => "Flexoki",
        ThemeId.Carbonfox => "Carbonfox",
        ThemeId.ShadesOfPurple => "Shades of Purple",
        ThemeId.Vercel => "Vercel",
        ThemeId.OsakaJade => "Osaka Jade",
        ThemeId.Amoled => "AMOLED",
        ThemeId.Mercury => "Mercury",
        ThemeId.Cursor => "Cursor",
        ThemeId.OneDarkPro => "One Dark Pro",
        ThemeId.Palenight => "Palenight",
        ThemeId.Orng => "Orng",
        ThemeId.Oc2 => "OC-2",
        ThemeId.AyuDark => "Ayu Dark",
        ThemeId.AyuLight => "Ayu Light",
        ThemeId.CatppuccinMacchiato => "Catppuccin Macchiato",
        ThemeId.MaterialOcean => "Material Ocean",
        ThemeId.MonokaiPro => "Monokai Pro",
        ThemeId.GitHubLight => "GitHub Light",
        ThemeId.WinterIsComing => "Winter Is Coming",
        ThemeId.OceanicNext => "Oceanic Next",
        ThemeId.Panda => "Panda",
        ThemeId.Darcula => "Darcula",
        ThemeId.DraculaPro => "Dracula Pro",
        ThemeId.Poimandres => "Poimandres",
        ThemeId.Horizon => "Horizon",
        ThemeId.Cyberpunk => "Cyberpunk",
        ThemeId.Snazzy => "Snazzy",
        ThemeId.NightOwlLight => "Night Owl Light",
        _ => "One Dark",
    };

    /// <summary>All themes, in the order shown in Settings.</summary>
    public static IReadOnlyList<ThemeId> All { get; } = new[]
    {
        ThemeId.OneDark,
        ThemeId.OneLight,
        ThemeId.FluentDark,
        ThemeId.FluentLight,
        ThemeId.Nord,
        ThemeId.Dracula,
        ThemeId.SolarizedDark,
        ThemeId.SolarizedLight,
        ThemeId.GruvboxDark,
        ThemeId.TokyoNight,
        ThemeId.Monokai,
        ThemeId.CatppuccinMocha,
        ThemeId.CatppuccinLatte,
        ThemeId.GitHubDark,
        ThemeId.MaterialPalenight,
        ThemeId.AyuMirage,
        ThemeId.RosePine,
        ThemeId.TokyoNightStorm,
        ThemeId.GruvboxLight,
        ThemeId.NightOwl,
        ThemeId.Cobalt2,
        ThemeId.EverforestDark,
        ThemeId.RosePineDawn,
        ThemeId.Synthwave84,
        ThemeId.Kanagawa,
        ThemeId.OpenCode,
        ThemeId.Vesper,
        ThemeId.Aura,
        ThemeId.Matrix,
        ThemeId.Zenburn,
        ThemeId.Flexoki,
        ThemeId.Carbonfox,
        ThemeId.ShadesOfPurple,
        ThemeId.Vercel,
        ThemeId.OsakaJade,
        ThemeId.Amoled,
        ThemeId.Mercury,
        ThemeId.Cursor,
        ThemeId.OneDarkPro,
        ThemeId.Palenight,
        ThemeId.Orng,
        ThemeId.Oc2,
        ThemeId.AyuDark,
        ThemeId.AyuLight,
        ThemeId.CatppuccinMacchiato,
        ThemeId.MaterialOcean,
        ThemeId.MonokaiPro,
        ThemeId.GitHubLight,
        ThemeId.WinterIsComing,
        ThemeId.OceanicNext,
        ThemeId.Panda,
        ThemeId.Darcula,
        ThemeId.DraculaPro,
        ThemeId.Poimandres,
        ThemeId.Horizon,
        ThemeId.Cyberpunk,
        ThemeId.Snazzy,
        ThemeId.NightOwlLight,
    };

    /// <summary>Parse a slug back to a <see cref="ThemeId"/>; null if unknown.</summary>
    public static ThemeId? FromSlug(string? slug) => slug?.ToLowerInvariant() switch
    {
        "one-dark" => ThemeId.OneDark,
        "one-light" => ThemeId.OneLight,
        "fluent-dark" => ThemeId.FluentDark,
        "fluent-light" => ThemeId.FluentLight,
        "nord" => ThemeId.Nord,
        "dracula" => ThemeId.Dracula,
        "solarized-dark" => ThemeId.SolarizedDark,
        "solarized-light" => ThemeId.SolarizedLight,
        "gruvbox-dark" => ThemeId.GruvboxDark,
        "tokyo-night" => ThemeId.TokyoNight,
        "monokai" => ThemeId.Monokai,
        "catppuccin-mocha" => ThemeId.CatppuccinMocha,
        "catppuccin-latte" => ThemeId.CatppuccinLatte,
        "github-dark" => ThemeId.GitHubDark,
        "material-palenight" => ThemeId.MaterialPalenight,
        "ayu-mirage" => ThemeId.AyuMirage,
        "rose-pine" => ThemeId.RosePine,
        "tokyo-night-storm" => ThemeId.TokyoNightStorm,
        "gruvbox-light" => ThemeId.GruvboxLight,
        "night-owl" => ThemeId.NightOwl,
        "cobalt2" => ThemeId.Cobalt2,
        "everforest-dark" => ThemeId.EverforestDark,
        "rose-pine-dawn" => ThemeId.RosePineDawn,
        "synthwave-84" => ThemeId.Synthwave84,
        "kanagawa" => ThemeId.Kanagawa,
        "opencode" => ThemeId.OpenCode,
        "vesper" => ThemeId.Vesper,
        "aura" => ThemeId.Aura,
        "matrix" => ThemeId.Matrix,
        "zenburn" => ThemeId.Zenburn,
        "flexoki" => ThemeId.Flexoki,
        "carbonfox" => ThemeId.Carbonfox,
        "shades-of-purple" => ThemeId.ShadesOfPurple,
        "vercel" => ThemeId.Vercel,
        "osaka-jade" => ThemeId.OsakaJade,
        "amoled" => ThemeId.Amoled,
        "mercury" => ThemeId.Mercury,
        "cursor" => ThemeId.Cursor,
        "one-dark-pro" => ThemeId.OneDarkPro,
        "palenight" => ThemeId.Palenight,
        "orng" => ThemeId.Orng,
        "oc-2" => ThemeId.Oc2,
        "ayu-dark" => ThemeId.AyuDark,
        "ayu-light" => ThemeId.AyuLight,
        "catppuccin-macchiato" => ThemeId.CatppuccinMacchiato,
        "material-ocean" => ThemeId.MaterialOcean,
        "monokai-pro" => ThemeId.MonokaiPro,
        "github-light" => ThemeId.GitHubLight,
        "winter-is-coming" => ThemeId.WinterIsComing,
        "oceanic-next" => ThemeId.OceanicNext,
        "panda" => ThemeId.Panda,
        "darcula" => ThemeId.Darcula,
        "dracula-pro" => ThemeId.DraculaPro,
        "poimandres" => ThemeId.Poimandres,
        "horizon" => ThemeId.Horizon,
        "cyberpunk" => ThemeId.Cyberpunk,
        "snazzy" => ThemeId.Snazzy,
        "night-owl-light" => ThemeId.NightOwlLight,
        _ => null,
    };
}
