# Single source of truth: tools/palettes.json (theme name -> 15 named colors).
# This generator emits, from that JSON:
#   * src/AiUsageBar.Core/Theming/PaletteColors.cs   (always)
#   * src/AiUsageBar.AvaloniaApp/Themes/Palettes/OneDark.axaml (when that project dir exists)
#
# The Avalonia head builds every palette at runtime from PaletteColors.cs (the AOT-safe
# path), so it needs only OneDark.axaml — the compile-time default merged at index 0 of
# App.axaml before AvaloniaThemeService swaps it. The other palettes are NOT emitted as
# .axaml because they would be embedded but never loaded.
#
# The JSON key equals the ThemeId enum member name, so it maps straight to `ThemeId.<key>`
# and to the `<key>.axaml` file name.
#
# Usage:  pwsh tools/Generate-Palettes.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$json = Get-Content (Join-Path $PSScriptRoot 'palettes.json') -Raw | ConvertFrom-Json -AsHashtable

# Canonical order: brush-key -> C# record property name. Order matters (positional record).
$map = [ordered]@{
  'BgBrush'='Bg'; 'Bg2Brush'='Bg2'; 'Bg3Brush'='Bg3'; 'HoverBrush'='Hover'; 'FgBrush'='Fg'
  'DimBrush'='Dim'; 'AccentBrush'='Accent'; 'BorderBrush'='Border'; 'BarEmptyBrush'='BarEmpty'
  'SevLowBrush'='SevLow'; 'SevMidBrush'='SevMid'; 'SevHighBrush'='SevHigh'
  'SevCriticalBrush'='SevCritical'; 'CloseHoverBrush'='CloseHover'; 'ClosePressedBrush'='ClosePressed'
}
$keys = @($map.Keys)
$names = $json.Keys | Sort-Object

# ---- PaletteColors.cs -------------------------------------------------------
$ctorParams = ($map.Values | ForEach-Object { "string $_" }) -join ', '
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('using AiUsageBar.Core.Models;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace AiUsageBar.Core.Theming;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/// <summary>')
[void]$sb.AppendLine('/// The 15 named colors of a theme palette, as #RRGGBB hex strings. Single source of')
[void]$sb.AppendLine('/// truth shared by the UI: the Avalonia palette dictionaries (*.axaml) and the')
[void]$sb.AppendLine('/// Settings theme swatches all derive from this table.')
[void]$sb.AppendLine('/// Generated by tools/Generate-Palettes.ps1 from tools/palettes.json — do not edit by hand.')
[void]$sb.AppendLine('/// </summary>')
[void]$sb.AppendLine("public sealed record PaletteColors($ctorParams)")
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    /// <summary>Palette colors for every theme, keyed by id.</summary>')
[void]$sb.AppendLine('    public static IReadOnlyDictionary<ThemeId, PaletteColors> All { get; } = new Dictionary<ThemeId, PaletteColors>')
[void]$sb.AppendLine('    {')
foreach ($name in $names) {
  $p = $json[$name]
  $args = ($keys | ForEach-Object { '"' + $p[$_] + '"' }) -join ', '
  [void]$sb.AppendLine("        [ThemeId.$name] = new($args),")
}
[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    /// <summary>The palette for a theme (falls back to One Dark for an unknown id).</summary>')
[void]$sb.AppendLine('    public static PaletteColors For(ThemeId id) => All.TryGetValue(id, out var p) ? p : All[ThemeId.OneDark];')
[void]$sb.AppendLine('}')

$coreOut = Join-Path $root 'src/AiUsageBar.Core/Theming'
if (-not (Test-Path $coreOut)) { New-Item -ItemType Directory -Force $coreOut | Out-Null }
$sb.ToString() | Set-Content -Path (Join-Path $coreOut 'PaletteColors.cs') -Encoding UTF8 -NoNewline
Write-Host "Wrote PaletteColors.cs ($($names.Count) themes)"

# ---- per-framework dictionaries --------------------------------------------
function Write-Dict($dir, $ext, $headerNs, $onlyNames = $null) {
  if (-not (Test-Path $dir)) { return $false }
  $emit = if ($onlyNames) { $names | Where-Object { $onlyNames -contains $_ } } else { $names }
  foreach ($name in $emit) {
    $p = $json[$name]
    $d = [System.Text.StringBuilder]::new()
    [void]$d.AppendLine('<ResourceDictionary ' + $headerNs + '>')
    [void]$d.AppendLine("    <!-- $name. Generated from tools/palettes.json — do not edit by hand. -->")
    foreach ($k in $keys) {
      # Pad the whole x:Key="..." attribute (not the key itself) so Color lines align
      # without injecting trailing spaces into the resource key.
      $keyAttr = ('x:Key="' + $k + '"').PadRight(26)
      [void]$d.AppendLine("    <SolidColorBrush $keyAttr Color=`"$($p[$k])`"/>")
    }
    [void]$d.AppendLine('</ResourceDictionary>')
    $d.ToString() | Set-Content -Path (Join-Path $dir "$name$ext") -Encoding UTF8 -NoNewline
  }
  return $true
}

$avaloniaNs = 'xmlns="https://github.com/avaloniaui"' + "`n                    " + 'xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"'
if (Write-Dict (Join-Path $root 'src/AiUsageBar.AvaloniaApp/Themes/Palettes') '.axaml' $avaloniaNs @('OneDark')) {
  Write-Host "Wrote Avalonia OneDark.axaml (bootstrap default; runtime palettes come from PaletteColors.cs)"
}
